[package]
name = "reductor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#chumsky = "0.9.3"
nom = "7.1.3"
